#!/usr/bin/env node

var argv = require('yargs').argv;
var opn = require('opn');
var YAML = require('yamljs');
var q = require('q');

var opts = {}
var modules = {}


q.fcall(loadOptions)
.then(function() { if (opts.debug) console.log("Running in debug mode.") })
.then(loadGit)
.then(loadServer)
.then(finishedPreload)
.done();



function finishedPreload(){
    console.log("Starting web server.");
    modules.server(opts, modules); 
    ready(opts);
}

function loadOptions(){
    
    var yaml = YAML.load('config.yml');

    opts = {
        version: "0.3",
        debug: argv.debug || yaml.debug || false,
        host: argv.host || yaml.host ||  "localhost",
        port: argv.port || yaml.port || 8000,
        
        //if the host is not 0.0.0.0 we should set the url to localhost
        url: (argv.host !== undefined && argv.host!=="0.0.0.0")?argv.host:"localhost",

        // should we open a browser
        headed: argv.headed || false,
        data: argv.data || "./data",
        cache: argv.cache || "./cache",

        //how often we should make a checkpoint automatically
        checkpoint: argv.checkpoint || 60
    }

}


function loadGit(){
    var git = require("./lib/git.js")(opts, modules);
    modules["git"] = git;
    if(opts.debug) console.log("Loaded Git.");
}

function loadServer(){
    var server = require('./lib/server.js');
    modules.server = server;
    if(opts.debug) console.log('Loaded Server.');
}

function ready(opts){
    if(opts.headed){
        console.log("Launching browser."); 
        var url = "http://" + opts["url"] + ":" + opts["port"];
        console.log("Opening: " + url + ".")
        opn(url)
    }
}
